version: '3.8'
services:
  account:
    build:
      context: ./artifacts/account/app
    depends_on:
      - redis
      - mongodb
      - opa
    environment:
      - REDIS_URI=redis://redis:6379
      - MONGO_URI=mongodb://mongodb:27017/
      - OPA_URI=http://opa:8181
    ports:
      - 5003:5003
      - 5033:5033

  auth:
    build:
      context: ./artifacts/auth/app
    depends_on:
      - redis
      - mongodb
      - opa
    environment:
      - REDIS_URI=redis://redis:6379
      - MONGO_URI=mongodb://mongodb:27017/
      - OPA_URI=http://opa:8181
    ports:
      - 5066:5066

  connection:
    build:
      context: ./artifacts/connection/app
    depends_on:
      - redis
      - mongodb
      - opa
    environment:
      - REDIS_URI=redis://redis:6379
      - MONGO_URI=mongodb://mongodb:27017/
      - OPA_URI=http://opa:8181
    ports:
      - 5005:5005
      - 5055:5055

  member:
    build:
      context: ./artifacts/member/app
    depends_on:
      - redis
      - mongodb
      - opa
    environment:
      - REDIS_URI=redis://redis:6379
      - MONGO_URI=mongodb://mongodb:27017/
      - OPA_URI=http://opa:8181
    ports:
      - 5004:5004
      - 5044:5044

  org:
    build:
      context: ./artifacts/org/app
    depends_on:
      - redis
      - mongodb
      - opa
    environment:
      - REDIS_URI=redis://redis:6379
      - MONGO_URI=mongodb://mongodb:27017/
      - OPA_URI=http://opa:8181
    ports:
      - 5001:5001
      - 5011:5011

  user:
    build:
      context: ./artifacts/user/app
    depends_on:
      - redis
      - mongodb
      - opa
    environment:
      - REDIS_URI=redis://redis:6379
      - MONGO_URI=mongodb://mongodb:27017/
      - OPA_URI=http://opa:8181
    ports:
      - 5002:5002
      - 5022:5022

  redis:
    image: redis:latest
    ports:
     - 6379:6379

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  opa:
    image: openpolicyagent/opa:latest
    command: "run --server"
    ports:
      - "8181:8181"
