version: '3.8'
services:
  account:
    build:
      context: ./artifacts/account/app
    environment:
      - REDIS_URI=redis://redis:6379
      - MONGO_URI=mongodb://mongodb:27017/
      - OPA_URI=http://opa:8181
    ports:
      - 5003:9090
      - 5033:80

  auth:
    build:
      context: ./artifacts/auth/app
    environment:
      - REDIS_URI=redis://redis:6379
      - MONGO_URI=mongodb://mongodb:27017/
      - OPA_URI=http://opa:8181
    ports:
      - 5066:80

  connection:
    build:
      context: ./artifacts/connection/app
    environment:
      - REDIS_URI=redis://redis:6379
      - MONGO_URI=mongodb://mongodb:27017/
      - OPA_URI=http://opa:8181
    ports:
      - 5005:9090
      - 5055:80

  member:
    build:
      context: ./artifacts/member/app
    environment:
      - REDIS_URI=redis://redis:6379
      - MONGO_URI=mongodb://mongodb:27017/
      - OPA_URI=http://opa:8181
    ports:
      - 5004:9090
      - 5044:80

  org:
    build:
      context: ./artifacts/org/app
    environment:
      - REDIS_URI=redis://redis:6379
      - MONGO_URI=mongodb://mongodb:27017/
      - OPA_URI=http://opa:8181
    ports:
      - 5001:9090
      - 5011:80

  user:
    build:
      context: ./artifacts/user/app
    environment:
      - REDIS_URI=redis://redis:6379
      - MONGO_URI=mongodb://mongodb:27017/
      - OPA_URI=http://opa:8181
    ports:
      - 5002:9090
      - 5022:80

  redis:
    image: redis:latest
    ports:
     - 6379:6379

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  opa:
    image: openpolicyagent/opa:latest
    command: "run --server"
    ports:
      - "8181:8181"
