version: '3.8'
services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PATH: dist/apps/auth
    depends_on:
      - redis
      - mongodb
      - opa
    environment:
      - REDIS_URI=redis://redis:6379
      - MONGO_URI=mongodb://mongodb:27017/
      - OPA_URI=http://opa:8181
      - SERVICE_NAME=auth

  connection:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PATH: dist/apps/org-connection
    depends_on:
      - redis
      - mongodb
      - opa
    environment:
      - REDIS_URI=redis://redis:6379
      - MONGO_URI=mongodb://mongodb:27017/
      - OPA_URI=http://opa:8181
      - SERVICE_NAME=org-connection

  member:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PATH: dist/apps/org-member
    depends_on:
      - redis
      - mongodb
      - opa
    environment:
      - REDIS_URI=redis://redis:6379
      - MONGO_URI=mongodb://mongodb:27017/
      - OPA_URI=http://opa:8181
      - SERVICE_NAME=org-member

  org:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PATH: dist/apps/org
    depends_on:
      - redis
      - mongodb
      - opa
    environment:
      - REDIS_URI=redis://redis:6379
      - MONGO_URI=mongodb://mongodb:27017/
      - OPA_URI=http://opa:8181
      - SERVICE_NAME=org

  user:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PATH: dist/apps/user
    depends_on:
      - redis
      - mongodb
      - opa
    environment:
      - REDIS_URI=redis://redis:6379
      - MONGO_URI=mongodb://mongodb:27017/
      - OPA_URI=http://opa:8181
      - SERVICE_NAME=user

  account:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PATH: dist/apps/user-account
    depends_on:
      - redis
      - mongodb
      - opa
    environment:
      - REDIS_URI=redis://redis:6379
      - MONGO_URI=mongodb://mongodb:27017/
      - OPA_URI=http://opa:8181
      - SERVICE_NAME=user-account

  redis:
    image: redis:latest
    ports:
     - 6379:6379

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  opa:
    image: openpolicyagent/opa:latest
    command: "run --server"
    ports:
      - "8181:8181"
