apiVersion: v1
kind: Service
metadata:
  name: service-org-member
spec:
  selector:
    app: service-org-member
  ports:
  - name: health
    protocol: TCP
    port: 80
    targetPort: 80
  - name: grpc
    protocol: TCP
    port: 50051
    targetPort: 50051
