apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-org-member
  labels:
    app: service-org-member
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-org-member
  template:
    metadata:
      labels:
        app: service-org-member
    spec:
      imagePullSecrets:
      - name: bpk8
      containers:
      - name: service-org-member
        image: registry.digitalocean.com/bpk8/service-org-member:latest
        ports:
        - containerPort: 80
        - containerPort: 50051
        livenessProbe:
          httpGet:
            path: /health
            port: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 80
        env:
        - name: NODE_ENV
          value: production
        - name: SERVICE_NAME
          value: org-member
        envFrom:
        - secretRef:
            name: application-secrets
        
