apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service }}-grpc-service
spec:
  selector:
    app: {{ .Values.service }}
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: LoadBalancer
