apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service }}-http-service
spec:
  selector:
    app: {{ .Values.service }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
