apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-auth
  namespace: application
  labels:
    app: service-auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-auth
  template:
    metadata:
      labels:
        app: service-auth
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service-port: "80"
        consul.hashicorp.com/transparent-proxy: "true"
    spec:
      imagePullSecrets:
      - name: bpk8
      containers:
      - name: service-auth
        image: registry.digitalocean.com/bpk8/service-auth:latest
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /health
            port: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 80
        env:
        - name: NODE_ENV
          value: production
        - name: SERVICE_NAME
          value: auth
        envFrom:
        - secretRef:
            name: application-secrets
        
