apiVersion: v1
kind: Service
metadata:
  name: service-auth
  namespace: application
spec:
  selector:
    app: service-auth
  ports:
  - name: health
    protocol: TCP
    port: 80
    targetPort: 80
  - name: grpc
    protocol: TCP
    port: 50051
    targetPort: 50051
