apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-user-account
  labels:
    app: service-user-account
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-user-account
  template:
    metadata:
      labels:
        app: service-user-account
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service-port: "50010"
        consul.hashicorp.com/transparent-proxy: "false"
    spec:
      imagePullSecrets:
      - name: bpk8
      containers:
      - name: service-user-account
        image: registry.digitalocean.com/bpk8/service-user-account:latest
        ports:
        - containerPort: 80
        - containerPort: 50051
        livenessProbe:
          httpGet:
            path: /health
            port: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 80
        env:
        - name: NODE_ENV
          value: production
        - name: SERVICE_NAME
          value: user-account
        envFrom:
        - secretRef:
            name: application-secrets
        
