apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service }}-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.service }}
  template:
    metadata:
      labels:
        app: {{ .Values.service }}
    spec:
      containers:
        - name: {{ .Values.service }}-container
          image: {{ .Values.image }}
          env:
            - name: SERVICE_NAME
              value: {{ .Values.service }}
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: session-secret
                  key: SESSION_SECRET
          ports:
            - name: http
              containerPort: 80
            - name: grpc
              containerPort: 9090
