apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-http
  labels:
    app: service-http
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-http
  template:
    metadata:
      labels:
        app: service-http
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service-port: 80
        consul.hashicorp.com/transparent-proxy: 80
    spec:
      imagePullSecrets:
      - name: bpk8
      containers:
      - name: service-http
        image: registry.digitalocean.com/bpk8/service-http:latest
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /health
            port: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 80
        env:
        - name: NODE_ENV
          value: production
        - name: SERVICE_NAME
          value: http
        envFrom:
        - secretRef:
            name: application-secrets
        
