apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-notify
  labels:
    app: service-notify
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-notify
  template:
    metadata:
      labels:
        app: service-notify
    spec:
      containers:
      - name: service-notify
        image: registry.digitalocean.com/bpk8/service-notify:latest
        ports:
        - containerPort: 80
        - containerPort: 50051
        livenessProbe:
          httpGet:
            path: /health
            port: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 80
        env:
        - name: NODE_ENV
          value: production
        - name: SERVICE_NAME
          value: notify
        envFrom:
        - secretRef:
            name: application-secrets
        
