apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-auth
  namespace: application
  annotations:
    argocd-image-updater.argoproj.io/image-list: "image=registry.digitalocean.com/bpk8/service-auth"
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/image.update-strategy: latest
spec:
  project: backend-services
  source:
    repoURL: 'git@github.com:bpofficial/backend-services.git'
    path: apps/auth/infra
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: application
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
