apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-notify
  namespace: application
spec:
  project: default
  source:
    repoURL: 'https://your-git-repository-url.git'
    path: apps/notify
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: application
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
